/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodersIndexRouteImport } from './routes/coders.index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as OnboardingCoderRouteImport } from './routes/onboarding.coder'
import { Route as EarningsCoderIdRouteImport } from './routes/earnings.$coderId'
import { Route as CodersCoderIdRouteImport } from './routes/coders.$coderId'
import { Route as CodersCoderIdSettingsRouteImport } from './routes/coders.$coderId.settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersIndexRoute = CodersIndexRouteImport.update({
  id: '/coders/',
  path: '/coders/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCoderRoute = OnboardingCoderRouteImport.update({
  id: '/onboarding/coder',
  path: '/onboarding/coder',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsCoderIdRoute = EarningsCoderIdRouteImport.update({
  id: '/earnings/$coderId',
  path: '/earnings/$coderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersCoderIdRoute = CodersCoderIdRouteImport.update({
  id: '/coders/$coderId',
  path: '/coders/$coderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersCoderIdSettingsRoute = CodersCoderIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CodersCoderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/coders/$coderId': typeof CodersCoderIdRouteWithChildren
  '/earnings/$coderId': typeof EarningsCoderIdRoute
  '/onboarding/coder': typeof OnboardingCoderRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coders/': typeof CodersIndexRoute
  '/coders/$coderId/settings': typeof CodersCoderIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/coders/$coderId': typeof CodersCoderIdRouteWithChildren
  '/earnings/$coderId': typeof EarningsCoderIdRoute
  '/onboarding/coder': typeof OnboardingCoderRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coders': typeof CodersIndexRoute
  '/coders/$coderId/settings': typeof CodersCoderIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/coders/$coderId': typeof CodersCoderIdRouteWithChildren
  '/earnings/$coderId': typeof EarningsCoderIdRoute
  '/onboarding/coder': typeof OnboardingCoderRoute
  '/projects/new': typeof ProjectsNewRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coders/': typeof CodersIndexRoute
  '/coders/$coderId/settings': typeof CodersCoderIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/coders/$coderId'
    | '/earnings/$coderId'
    | '/onboarding/coder'
    | '/projects/new'
    | '/workspaces/$workspaceId'
    | '/coders/'
    | '/coders/$coderId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/coders/$coderId'
    | '/earnings/$coderId'
    | '/onboarding/coder'
    | '/projects/new'
    | '/workspaces/$workspaceId'
    | '/coders'
    | '/coders/$coderId/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/coders/$coderId'
    | '/earnings/$coderId'
    | '/onboarding/coder'
    | '/projects/new'
    | '/workspaces/$workspaceId'
    | '/coders/'
    | '/coders/$coderId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CodersCoderIdRoute: typeof CodersCoderIdRouteWithChildren
  EarningsCoderIdRoute: typeof EarningsCoderIdRoute
  OnboardingCoderRoute: typeof OnboardingCoderRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  CodersIndexRoute: typeof CodersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/': {
      id: '/coders/'
      path: '/coders'
      fullPath: '/coders/'
      preLoaderRoute: typeof CodersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/coder': {
      id: '/onboarding/coder'
      path: '/onboarding/coder'
      fullPath: '/onboarding/coder'
      preLoaderRoute: typeof OnboardingCoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings/$coderId': {
      id: '/earnings/$coderId'
      path: '/earnings/$coderId'
      fullPath: '/earnings/$coderId'
      preLoaderRoute: typeof EarningsCoderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/$coderId': {
      id: '/coders/$coderId'
      path: '/coders/$coderId'
      fullPath: '/coders/$coderId'
      preLoaderRoute: typeof CodersCoderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/$coderId/settings': {
      id: '/coders/$coderId/settings'
      path: '/settings'
      fullPath: '/coders/$coderId/settings'
      preLoaderRoute: typeof CodersCoderIdSettingsRouteImport
      parentRoute: typeof CodersCoderIdRoute
    }
  }
}

interface CodersCoderIdRouteChildren {
  CodersCoderIdSettingsRoute: typeof CodersCoderIdSettingsRoute
}

const CodersCoderIdRouteChildren: CodersCoderIdRouteChildren = {
  CodersCoderIdSettingsRoute: CodersCoderIdSettingsRoute,
}

const CodersCoderIdRouteWithChildren = CodersCoderIdRoute._addFileChildren(
  CodersCoderIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CodersCoderIdRoute: CodersCoderIdRouteWithChildren,
  EarningsCoderIdRoute: EarningsCoderIdRoute,
  OnboardingCoderRoute: OnboardingCoderRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  CodersIndexRoute: CodersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
