/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodersIndexRouteImport } from './routes/coders.index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as EarningsCoderIdRouteImport } from './routes/earnings.$coderId'
import { Route as CodersCoderIdRouteImport } from './routes/coders.$coderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersIndexRoute = CodersIndexRouteImport.update({
  id: '/coders/',
  path: '/coders/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsCoderIdRoute = EarningsCoderIdRouteImport.update({
  id: '/earnings/$coderId',
  path: '/earnings/$coderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersCoderIdRoute = CodersCoderIdRouteImport.update({
  id: '/coders/$coderId',
  path: '/coders/$coderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coders/$coderId': typeof CodersCoderIdRoute
  '/earnings/$coderId': typeof EarningsCoderIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coders/': typeof CodersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coders/$coderId': typeof CodersCoderIdRoute
  '/earnings/$coderId': typeof EarningsCoderIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coders': typeof CodersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coders/$coderId': typeof CodersCoderIdRoute
  '/earnings/$coderId': typeof EarningsCoderIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coders/': typeof CodersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coders/$coderId'
    | '/earnings/$coderId'
    | '/workspaces/$workspaceId'
    | '/coders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coders/$coderId'
    | '/earnings/$coderId'
    | '/workspaces/$workspaceId'
    | '/coders'
  id:
    | '__root__'
    | '/'
    | '/coders/$coderId'
    | '/earnings/$coderId'
    | '/workspaces/$workspaceId'
    | '/coders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodersCoderIdRoute: typeof CodersCoderIdRoute
  EarningsCoderIdRoute: typeof EarningsCoderIdRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  CodersIndexRoute: typeof CodersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/': {
      id: '/coders/'
      path: '/coders'
      fullPath: '/coders/'
      preLoaderRoute: typeof CodersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings/$coderId': {
      id: '/earnings/$coderId'
      path: '/earnings/$coderId'
      fullPath: '/earnings/$coderId'
      preLoaderRoute: typeof EarningsCoderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/$coderId': {
      id: '/coders/$coderId'
      path: '/coders/$coderId'
      fullPath: '/coders/$coderId'
      preLoaderRoute: typeof CodersCoderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodersCoderIdRoute: CodersCoderIdRoute,
  EarningsCoderIdRoute: EarningsCoderIdRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  CodersIndexRoute: CodersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
