/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodersIndexRouteImport } from './routes/coders.index'
import { Route as CodersCoderIdRouteImport } from './routes/coders.$coderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersIndexRoute = CodersIndexRouteImport.update({
  id: '/coders/',
  path: '/coders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodersCoderIdRoute = CodersCoderIdRouteImport.update({
  id: '/coders/$coderId',
  path: '/coders/$coderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coders/$coderId': typeof CodersCoderIdRoute
  '/coders/': typeof CodersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coders/$coderId': typeof CodersCoderIdRoute
  '/coders': typeof CodersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coders/$coderId': typeof CodersCoderIdRoute
  '/coders/': typeof CodersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coders/$coderId' | '/coders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coders/$coderId' | '/coders'
  id: '__root__' | '/' | '/coders/$coderId' | '/coders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodersCoderIdRoute: typeof CodersCoderIdRoute
  CodersIndexRoute: typeof CodersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/': {
      id: '/coders/'
      path: '/coders'
      fullPath: '/coders/'
      preLoaderRoute: typeof CodersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coders/$coderId': {
      id: '/coders/$coderId'
      path: '/coders/$coderId'
      fullPath: '/coders/$coderId'
      preLoaderRoute: typeof CodersCoderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodersCoderIdRoute: CodersCoderIdRoute,
  CodersIndexRoute: CodersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
